// surfaces/business/text.ts (WP7b) — Secretary texts (module-private, en + ru; 04 §2 i18n: text no other WP needs
// stays in the module and picks its language with uiLang()). Every `{x}` value is escaped by the caller.
import { uiLang } from '../../contracts/index.ts';

const EN = {
  consent_title: '🤝 **Gora is connected to your account (Chat Automation).**',
  consent_body:
    'Until you enable AI for a chat I only note *when* messages arrive — no content. For chats you enable: message text is stored encrypted for 30 days and sent to {processor} to triage and draft replies. **Nothing is ever sent without your tap.** Every read, draft and send is in your Ledger.',
  consent_version: 'Consent text {version}.',
  btn_choose: '⚙️ Choose chats',
  btn_all_new: '✅ AI for all new chats',
  btn_keep_off: 'Keep AI off',
  new_chats_on: 'AI is on for new chats. Existing chats stay off until you enable them.',
  ai_kept_off: 'OK — AI stays off. Nothing is stored except arrival times.',
  disconnected:
    '🔌 Gora was disconnected from your account (Chat Automation). I stopped processing and deleted the Secretary data (chat list and stored messages).',
  reconnected: '🤝 Gora is connected to your account again. AI stays off until you enable it for chats.',
  no_connection: 'Connect Gora first: Telegram Settings → Chat Automation → Gora.',
  chat_card_title: '💬 **Secretary · {name}**',
  chat_ai_on: 'AI: on — messages are stored encrypted for 30 days, triaged and drafted.',
  chat_ai_off: 'AI: off — only arrival times are noted.',
  chat_mode: 'Mode: {mode}',
  mode_triage: 'triage (digest only)',
  mode_draft: 'draft (reply suggestions)',
  chat_tone: 'Tone notes: {state}',
  tone_set: 'set',
  tone_none: 'none',
  btn_enable: 'Enable AI here',
  btn_mode: 'Mode: {mode} ▾',
  btn_tone: 'Tone notes…',
  btn_off: 'Off',
  chat_enabled: 'AI enabled for this chat.',
  chat_disabled: 'AI is off for this chat. Its stored messages and drafts were deleted.',
  mode_set: 'Mode: {mode}',
  tone_hint: 'Set tone notes in the Mini App → Secretary.',
  not_found: 'That chat is not available.',
  digest_title: '📥 **Secretary**',
  digest_empty: 'Nothing waiting for a reply.',
  digest_waiting: 'waiting since {time}',
  digest_window: 'reply window closes {when}',
  digest_no_draft: 'no reply suggested',
  urgency_3: '🔴 now',
  urgency_2: '🟠 today',
  urgency_1: '🟡 low',
  urgency_0: '⚪ info',
  btn_draft: '✍️ Draft: {name}',
  drafting: 'Drafting a reply…',
  draft_unavailable: 'Can’t draft now: the chat is off or its reply window is closed.',
  window_closed: '⌛ Telegram closed the 24 h reply window. Copy the draft and send it yourself:',
  window_void_reason: 'Telegram closed the 24 h reply window',
  btn_copy: '📋 Copy',
  diff_title: 'Reply to {name}',
  diff_summary: 'Reply to {name} in Telegram',
  diff_to: 'To',
  diff_last: 'Their last message',
  diff_draft: 'Draft',
  sent_summary: 'Sent to {name}',
  peer: 'the other person',
  unknown_chat: 'chat {id}',
} as const;

type Key = keyof typeof EN;

const RU: Record<Key, string> = {
  consent_title: '🤝 **Gora подключена к вашему аккаунту (Автоматизация чатов).**',
  consent_body:
    'Пока вы не включите ИИ для чата, я отмечаю только *время* сообщений — без содержания. Для включённых чатов: текст сообщений хранится зашифрованным 30 дней и отправляется в {processor} для сортировки и черновиков ответов. **Ничего не отправляется без вашего нажатия.** Каждое чтение, черновик и отправка — в вашем Журнале.',
  consent_version: 'Версия текста согласия {version}.',
  btn_choose: '⚙️ Выбрать чаты',
  btn_all_new: '✅ ИИ для всех новых чатов',
  btn_keep_off: 'Оставить ИИ выключенным',
  new_chats_on: 'ИИ включён для новых чатов. Существующие чаты выключены, пока вы их не включите.',
  ai_kept_off: 'Хорошо — ИИ выключен. Сохраняется только время сообщений.',
  disconnected:
    '🔌 Gora отключена от вашего аккаунта (Автоматизация чатов). Я остановила обработку и удалила данные Секретаря (список чатов и сохранённые сообщения).',
  reconnected: '🤝 Gora снова подключена к вашему аккаунту. ИИ выключен, пока вы не включите его для чатов.',
  no_connection: 'Сначала подключите Gora: Настройки Telegram → Автоматизация чатов → Gora.',
  chat_card_title: '💬 **Секретарь · {name}**',
  chat_ai_on: 'ИИ: включён — сообщения хранятся зашифрованными 30 дней, сортируются и получают черновики.',
  chat_ai_off: 'ИИ: выключен — отмечается только время сообщений.',
  chat_mode: 'Режим: {mode}',
  mode_triage: 'сортировка (только сводка)',
  mode_draft: 'черновики (предложения ответов)',
  chat_tone: 'Заметки о тоне: {state}',
  tone_set: 'есть',
  tone_none: 'нет',
  btn_enable: 'Включить ИИ здесь',
  btn_mode: 'Режим: {mode} ▾',
  btn_tone: 'Заметки о тоне…',
  btn_off: 'Выключить',
  chat_enabled: 'ИИ включён для этого чата.',
  chat_disabled: 'ИИ выключен для этого чата. Его сохранённые сообщения и черновики удалены.',
  mode_set: 'Режим: {mode}',
  tone_hint: 'Заметки о тоне задаются в мини-приложении → Секретарь.',
  not_found: 'Этот чат недоступен.',
  digest_title: '📥 **Секретарь**',
  digest_empty: 'Ничего не ждёт ответа.',
  digest_waiting: 'ждёт с {time}',
  digest_window: 'окно ответа закроется {when}',
  digest_no_draft: 'ответ не предложен',
  urgency_3: '🔴 срочно',
  urgency_2: '🟠 сегодня',
  urgency_1: '🟡 не срочно',
  urgency_0: '⚪ для сведения',
  btn_draft: '✍️ Черновик: {name}',
  drafting: 'Готовлю черновик…',
  draft_unavailable: 'Сейчас нельзя: чат выключен или окно ответа закрыто.',
  window_closed: '⌛ Telegram закрыл 24-часовое окно ответа. Скопируйте черновик и отправьте сами:',
  window_void_reason: 'Telegram закрыл 24-часовое окно ответа',
  btn_copy: '📋 Копировать',
  diff_title: 'Ответ для {name}',
  diff_summary: 'Ответ для {name} в Telegram',
  diff_to: 'Кому',
  diff_last: 'Их последнее сообщение',
  diff_draft: 'Черновик',
  sent_summary: 'Отправлено: {name}',
  peer: 'собеседник',
  unknown_chat: 'чат {id}',
};

export type BizTextKey = Key;

export function bt(key: Key, lang: string | null | undefined, vars: Record<string, string | number> = {}): string {
  const src: string = uiLang(lang) === 'ru' ? RU[key] : EN[key];
  return src.replace(/\{(\w+)\}/g, (m, k: string) => (k in vars ? String(vars[k]) : m));
}
